spring:
  application:
    name: sboot-vyne-atom-transaction
    description: CRUD - VYNE
  main:
    banner-mode: "off"
    lazy-initialization: true
    allow-bean-definition-overriding: true
  beaninfo:
    ignore: true
server:
  address: 0.0.0.0
  port: 8080
  error:
    whitelabel:
      enabled: false
management:
  server:
    port: 9090
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
---
# Settings for local development
spring:
  profiles:
    active: local

autoconfigure:
  exclude:
  - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
############ Settings for H2 ############
  h2:
    console:
      enabled: true
      path: /h2-console
      console.settings.trace: false
      spring.h2.console.settings.web-allow-others: false
  datasource:
    url: jdbc:h2:mem:vynedb;DB_CLOSE_DELAY=-1
    username: vyne
    password: vyne
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    spring.jpa.defer-datasource-initialization: true
    spring.jpa.hibernate.ddl-auto: create-drop
############ Settings for H2 ############
---

###Configure for another environment###